### ISSUE TITLE
php 8 compatibility ?

### ISSUE THREAD

**Issue by NodokaMurmevent** [shapecode/hidden-entity-type-bundle#10]
i use this for a long moment with php 8 without any problem i just need to use. --ignore-platform-reqs

it’s possible to update this bundle for assure a php8 compatibility ?

**Comment by nicklog** [comment]
Hey,

yes, i will do it by time 👍🏼

**Comment by danaki** [comment]
+1

**Comment by danaki** [comment]
Hello?

**Comment by nicklog** [comment]
here we are :) Feel free to use v5.0.0
