### ISSUE TITLE
Multiple null

### ISSUE THREAD

**Issue by victor-paumier** [shapecode/hidden-entity-type-bundle#3]
Hi,

I get an error saying `the new value must be an array or an instance of \Traversable, "NULL" given.` when I try to submit a form with a HiddenEntityType set with multiple => true with no data.

IMO, the [reverseTransform function](https://github.com/shapecode/hidden-entity-type-bundle/blob/8a1b63a74977b3d8a7e3913e2d2798165ca93350/src/Form/DataTransformer/ObjectToIdTransformer.php#L85) of the ObjectToIdTransformer class should return an empty array if the $id is null and isMultiple() is true instead of null to fix that. See below:

```
public function reverseTransform($id)
{
    if (!$id) {
        if ($this->isMultiple()) {
            return [];
        }

        return null;
    }
}
```

Or am I wrong and I missed something?
Thank you!

**Comment by nicklog** [comment]
Hey,

i take a look :)
