### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by Nexotap** [shapecode/hidden-entity-type-bundle#7]
Have tried to install this with composer, within a symfony 5 project.
The installation fails because not all requirements could be solved.

Since  "doctrine/doctrine-bundle": "^1.6" wont work with symfony5, can't you just modify that line in composer.json to : "doctrine/doctrine-bundle": "^1.6|^2.0" ?

Tried that out and it seems to work for me.

**Comment by nicklog** [comment]
doctrine/doctrine-bundle is not needed anymore

**Comment by Nexotap** [comment]
Thanks for fixing this that quick.
