### ISSUE TITLE
Deprecation message in new doctrine versions

### ISSUE THREAD

**Issue by tshadrin** [shapecode/hidden-entity-type-bundle#9]
The "Doctrine\Common\Persistence\ManagerRegistry" service alias is deprecated, use "Doctrine\Persistence\ManagerRegistry" instead. It is being referenced by the "Shapecode\Bundle\HiddenEntityTypeBundle\Form\Type\HiddenObjectType" service.

In new versions we are need use Doctrine\Persistence\ManagerRegistry instead Doctrine\Common\Persistence\ManagerRegistry in
Shapecode\Bundle\HiddenEntityTypeBundle\Form\Type\HiddenObjectType

**Comment by nicklog** [comment]
I guess you used an old version?
